### ISSUE TITLE
Does NRPN work?

### ISSUE THREAD

**Issue by electricmonk** [InvisibleWrench/FlutterMidiCommand#73]
I'm sending NRPN messages to a Sequential Rev2 synth connected to an iPhone running my app, using a BLE MIDI adapter ([MD-BT01](https://usa.yamaha.com/products/music_production/accessories/md-bt01/index.html)).

The synth is receiving the messages but the value is always interpreted as 0 value.

Sending an NRPN message from my DAW (Logic Pro X) works properly so I know that the synth is treating the NRPN according to its MIDI specification.

Are you sure that NRPN messages work as expected?

**Comment by mortenboye** [comment]
HI @electricmonk try the latest v0.4.10, i believe it works as intended

**Comment by electricmonk** [comment]
Wow. That was fast. I'll check soon.

**Comment by electricmonk** [comment]
Nope, same behavior.

I'm also getting an exception now:
```
    midiAdapter.sendNRPN(4097, 0);
flutter: received packet Instance of 'MidiPacket'
flutter: data [176, 32, 1] @ time 8039 from device MD-BT01:C9EA8012-9494-3CF3-39A6-3422BD93FEFD
flutter: got 3 bytes
flutter: received packet Instance of 'MidiPacket'
flutter: data [192, 3] @ time 8040 from device MD-BT01:C9EA8012-9494-3CF3-39A6-3422BD93FEFD
flutter: got 3 bytes
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 2: 2
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2268:7)
#1      FMCMidiAdapter.onControlMessage.<anonymous closure> (package:midi_set_list/midi/midi.dart:130:24)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#6      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#11     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by mortenboye** [comment]
Can you provide some more information?
What data are you sending?
If you connect to something that can log the midi data (could be your Mac), what data is being received?

**Comment by electricmonk** [comment]
I need to find some time, I’ll record the nrpn message from Logic to raw bytes and write a unit test, then submit a PR. On 26 Jan 2023, at 20:54, Morten Boye Mortensen ***@***.***> wrote:﻿
Can you provide some more information?
What data are you sending?
If you connect to something that can log the midi data (could be your Mac), what data is being received?

**Comment by maks** [comment]
For what its worth, I did successfully use nrpn's in my elfer project: https://github.com/maks/elfer but that was on linux & android only, I never tried running it on macos.

Elfers all very specific to the Korg Electribe E2 running the Hacktribe firmware but maybe this could be of some help? https://github.com/maks/elfer/blob/main/lib/midi/e2_device.dart#L191

**Comment by mortenboye** [comment]
@electricmonk perhaps you can give this commit a try https://github.com/InvisibleWrench/FlutterMidiCommand/commit/f874421419c474a0570ee0f5b8c5355abf54b402
I changed the NRPN message from sending bytes as Running Status to individual CC messages instead. Maybe that makes a difference?

**Comment by electricmonk** [comment]
Still no go.

see #74, I did a hex dump of a working NRPN message from Logic Pro to my synth, and wrote a unit test to assert the message.

It appears that you're not sending the last 3 bytes (data LSB) which according to a spec I just read seems to be optional but my synth doesn't respond to the message without it.

To corroborate I edited the raw MIDI message, removed the data LSB part and sent to my synth, and it indeed doesn't like it.

Since it's optional, would it hurt to always send it?

**Comment by mortenboye** [comment]
I'm surprised to learn that a Sequential synth doesn't understand NRPN without the optional value LSB byte. After all Sequential was founded by Dave Smith who also had a leading role in forming the MIDI spec.

Anyways, I'm reluctant to always send the optional valueMSB byte if it is not generally required. In fact I would prefer to always send the bytes as running status, and save 2-3 bytes with every message.

In your case it seems your synth does not follow the spec, so I would suggest you write your own MidiMessage subclass and send the exact bytes you need.

**Comment by mortenboye** [comment]
You are right about the value LSB being off. Thanks.

I just did some testing with some other equipment (I dont have a Rev2) and monitored some midi logs, and it leads me to believe that I've "overinterpreted" the NRPN spec.
I think that instead of a single NRPN message that decides to include the valueLSB based on the value instead it should be decided with the message type. Some parameters/controls seems to always send/receive 14 bit values (MSB+LSB) and some only 7 bit.
I will make an update that includes two types of NRPN messages.

**Comment by intonarumori** [comment]
I have both iOS and Android devices, a DSI Tetra and a Pioneer Toraiz AS-1 (both basically Sequential).

What I found:
- On iOS when sending the 9 byte NRPN style messages, it never arrives. Sending 4 separate 3 byte NRPN messages works fine
- On Android sending the 9 byte NRPN style message works, but the separate 3 byte messages don't

I also verified these results by running through an iConnectivity MIDI patchbay, where I can inspect all the messages.
For now I have a conditional when sending NRPN with the following:

```
if (Platform.isIOS) {
      // Send 4 separate 3 byte NRPN messages for ParamMSB, ParamLSB, ValueLSB, ValueLSB
      ...
} else if (Platform.isAndroid) {
      // Send 9 byte NRPN message with ParamMSB, ParamLSB, ValueLSB, ValueLSB in one message
      ...
}
```

It works for now, curious to hear more about your experience.
